[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
  inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = 'let g:go_fmt_command = "goimports"'

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['js', 'jsx']

# ts
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = 'let g:typescript_indent_disable = 0'

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_event = 'InsertEnter'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 3'

# html
[[plugin]]
repo = 'mattn/emmet-vim'
of_ft = ['html', 'xml']

[[plugins]]
repo = 'othree/html5.vim'
of_ft = ['html']

# elm
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rus']

