# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = 'let g:go_fmt_command = "goimports"'

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['js', 'jsx']

# ts
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = 'let g:typescript_indent_disable = 0'

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_event = 'InsertEnter'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 3'

# html
[[plugin]]
repo = 'mattn/emmet-vim'
of_ft = ['html', 'xml']

[[plugins]]
repo = 'othree/html5.vim'
of_ft = ['html']

# elm
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rus']

