# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = 'let g:go_fmt_command = "goimports"'

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js', 'jsx']
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['js', 'jsx']

# ts
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = 'let g:typescript_indent_disable = 0'

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_event = 'InsertEnter'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 3'

# html
[[plugin]]
repo = 'mattn/emmet-vim'
of_ft = ['html', 'xml']
